<?xml version="1.0"?>
<!DOCTYPE Woerterbucheintrag [
<!ELEMENT     Woerterbucheintrag          (Lemma, Ursprung?, Grammatik?, Definition*)>
<!ELEMENT     Lemma                       (Silbe+)>
<!ATTLIST     Lemma
         Ursprung               CDATA                         #IMPLIED> 
<!ELEMENT     Silbe                       ((Buchstabe-unbetont*|Buchstabe-betont?)+)>
<!ELEMENT     Buchstabe-unbetont          (#PCDATA)>
<!ELEMENT     Buchstabe-betont            (#PCDATA)>
<!ELEMENT     Grammatik                   (Deklinationstyp|Deklinationsinfo+)>
<!ATTLIST     Grammatik
         Genus                  (w|s|m)                       #REQUIRED>
<!ELEMENT     Deklinationstyp             EMPTY>
<!ATTLIST     Deklinationstyp  
         Nr                     NMTOKEN                       #REQUIRED>
<!ELEMENT     Deklinationsinfo            (#PCDATA)>
<!ATTLIST     Deklinationsinfo
         Kategorie              (Nom|Akk|Gen|Dat|Ez|Mz)       #REQUIRED>
<!ELEMENT     Definition                  (#PCDATA)>
]>
<Woerterbucheintrag>
  <Lemma>
    <Silbe>
      <Buchstabe-betont>E</Buchstabe-betont>
      <Buchstabe-unbetont>r</Buchstabe-unbetont>
      <Buchstabe-unbetont>b</Buchstabe-unbetont>
    </Silbe>
    <Silbe>
      <Buchstabe-unbetont>s</Buchstabe-unbetont>
      <Buchstabe-unbetont>e</Buchstabe-unbetont>
      <Buchstabe-unbetont>n</Buchstabe-unbetont>
    </Silbe>
    <Silbe>
      <Buchstabe-unbetont>b</Buchstabe-unbetont>
      <Buchstabe-unbetont>e</Buchstabe-unbetont>
      <Buchstabe-unbetont>i</Buchstabe-unbetont>
      <Buchstabe-unbetont>n</Buchstabe-unbetont>
    </Silbe>
  </Lemma>
  <Grammatik Genus="s">
      <Deklinationstyp Nr="1" />
  </Grammatik>
  <Definition>ein Handwurzelknochen</Definition>
</Woerterbucheintrag>