<?xml version="1.0"?>
<!DOCTYPE Woerterbucheintrag [
<!ELEMENT Woerterbucheintrag (Lemma, Ursprung?, Grammatik?, Definition*)>
<!ELEMENT Lemma (Silbe+)>
<!ELEMENT Silbe ((Buchstabe-unbetont*|Buchstabe-betont?)+)>
<!ELEMENT Buchstabe-unbetont (#PCDATA)>
<!ELEMENT Buchstabe-betont (#PCDATA)>
<!ELEMENT Ursprung (#PCDATA)>
<!ELEMENT Grammatik (Geschlecht, (Deklinationstyp|Deklinationsinfo+))>
<!ELEMENT Geschlecht (#PCDATA)>
<!ELEMENT Deklinationstyp (#PCDATA)>
<!ELEMENT Deklinationsinfo (Kategorie, Endung)>
<!ELEMENT Kategorie (#PCDATA)>
<!ELEMENT Endung (#PCDATA)>
<!ELEMENT Definition (#PCDATA)>
]>
<Woerterbucheintrag>
  <Lemma>
    <Silbe>
      <Buchstabe-betont>E</Buchstabe-betont>
      <Buchstabe-unbetont>r</Buchstabe-unbetont>
      <Buchstabe-unbetont>b</Buchstabe-unbetont>
    </Silbe>
    <Silbe>
      <Buchstabe-unbetont>s</Buchstabe-unbetont>
      <Buchstabe-unbetont>e</Buchstabe-unbetont>
    </Silbe>
  </Lemma>
  <Grammatik>
      <Geschlecht>w</Geschlecht>
      <Deklinationstyp>11</Deklinationstyp>
  </Grammatik>
</Woerterbucheintrag>